name: Schedule MedNews
on:
  workflow_dispatch:
  schedule:
    # Runs at 10:00 UTC (7:00 BRT) every day
    - cron: '0 10 * * *'
jobs:
  run-task:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python src/main.py
